<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [2]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [3]:
array_1d = np.random.randint(0,10,10)
array_1d

array([9, 4, 7, 8, 4, 0, 4, 4, 4, 0], dtype=int32)

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [4]:
array_2d = np.reshape(array_1d, (2, 5))
print(array_2d)

[[9 4 7 8 4]
 [0 4 4 4 0]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [5]:
array_init = [0, 2, 0, 3, 0, 4, 0]
array_ejer_3 = np.array(array_init)
result = array_ejer_3[array_ejer_3 !=  0]
result


array([2, 3, 4])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [6]:
array_tres_x_tres = np.random.randint(0,2,(3,3))
array_tres_x_tres

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [7]:
array_10_numeros = np.random.randint(0,10,10)
print(array_10_numeros)
minimo = np.min(array_10_numeros)
print(minimo)
maximo = np.max(array_10_numeros)
print(maximo)

[8 5 8 0 1 1 9 1 7 4]
0
9


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [8]:
una_dimension = np.random.randint(0,10,10)
print(una_dimension)
una_dimension_inver = una_dimension[::-1]
print(una_dimension_inver)

[2 4 9 6 3 0 1 2 9 8]
[8 9 2 1 0 3 6 9 4 2]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [9]:
array_tridimensional = np.random.randint(1,25,(2,3,4))
print("Todos: ")
print(array_tridimensional)

valor_buscar = 15
result_buscar = array_tridimensional[array_tridimensional ==  valor_buscar]

if len(result_buscar) > 0:
    print(result_buscar[0])
else:
    print(f"No hay valor buscado: {valor_buscar}")

print("Primer Array: ")
print(array_tridimensional[0, :, :])

print("Ultima FIla Array: ")
print(array_tridimensional[1, 2, :])


Todos: 
[[[10  1 16 20]
  [ 1  8 12 11]
  [ 7  5 14  5]]

 [[14  7 10 22]
  [13 21  1 15]
  [ 7 15 10  7]]]
15
Primer Array: 
[[10  1 16 20]
 [ 1  8 12 11]
 [ 7  5 14  5]]
Ultima FIla Array: 
[ 7 15 10  7]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [10]:
array_tridimensional_7 = np.random.randint(1,31,(3,2,5))
print("Todos: ")
print(array_tridimensional_7)

print("Primer subarray: ")
print(array_tridimensional_7[0, :, (0,1)])

print("Segundo subarray: ")
print(array_tridimensional_7[(1,2), :, :])

Todos: 
[[[29  1 16 16  7]
  [13 17 25  1 28]]

 [[ 4 18  1  4 13]
  [21 11 23 12 10]]

 [[22  2  3 12 20]
  [25  6 14 26 14]]]
Primer subarray: 
[[29 13]
 [ 1 17]]
Segundo subarray: 
[[[ 4 18  1  4 13]
  [21 11 23 12 10]]

 [[22  2  3 12 20]
  [25  6 14 26 14]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [11]:
array_tridimensional_8 = np.random.randint(1,31,(4,3,2))
print("Todos: ")
print(array_tridimensional_8)

array_tridimensional_8[1, 1, :] = 0
print("Cambiado: ")
print(array_tridimensional_8)


Todos: 
[[[17 27]
  [25 26]
  [28 16]]

 [[15 27]
  [30 17]
  [29  7]]

 [[18 29]
  [20 29]
  [ 9 30]]

 [[28  2]
  [30 26]
  [24 12]]]
Cambiado: 
[[[17 27]
  [25 26]
  [28 16]]

 [[15 27]
  [ 0  0]
  [29  7]]

 [[18 29]
  [20 29]
  [ 9 30]]

 [[28  2]
  [30 26]
  [24 12]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [12]:
array_tridimensional_9 = np.random.randint(-10,14,(2,4,3))
print("Todos: ")
print(array_tridimensional_9)
resultado_9 = array_tridimensional_9[array_tridimensional_9 > 9]
print("Resultado: ")
print(resultado_9)
array_tridimensional_9[array_tridimensional_9 <  0 ] = 0
print(array_tridimensional_9)


Todos: 
[[[  1   3  12]
  [  3   3  -1]
  [ -9   8   6]
  [ -4  12  -4]]

 [[ -9  11   1]
  [ -3   7  -7]
  [ 12 -10   8]
  [  6  -9  -6]]]
Resultado: 
[12 12 11 12]
[[[ 1  3 12]
  [ 3  3  0]
  [ 0  8  6]
  [ 0 12  0]]

 [[ 0 11  1]
  [ 0  7  0]
  [12  0  8]
  [ 6  0  0]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [13]:
array_tridimensional_10 = np.random.randint(1,28,(3,3,3))
print("Todos: ")
print(array_tridimensional_10)

print("segundo array")
print(array_tridimensional_10[1, :, (0,1)])

array_tridimensional_10_tercer_array = array_tridimensional_10[2, :, :]
print("todos los del tercer array")
print(array_tridimensional_10_tercer_array)

array_tridimensional_10_tercer_array[array_tridimensional_10_tercer_array > 20]


Todos: 
[[[19 14  3]
  [16 14  3]
  [18  1  6]]

 [[22 15 11]
  [16 15 22]
  [ 2  8 13]]

 [[ 5 25  8]
  [24 18 22]
  [14 13  2]]]
segundo array
[[22 16  2]
 [15 15  8]]
todos los del tercer array
[[ 5 25  8]
 [24 18 22]
 [14 13  2]]


array([25, 24, 22], dtype=int32)

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [14]:
array_tridimensional_11 = np.random.randint(1,30,10)
print(array_tridimensional_11)
maximo = np.max(array_tridimensional_11)
minimo = np.min(array_tridimensional_11)
print(maximo)
print(minimo)

array_tridimensional_11[array_tridimensional_11 == maximo] = 0
array_tridimensional_11[array_tridimensional_11 == minimo] = 0
print(array_tridimensional_11)



[ 6  7 16 12 29 18 27 25 19 26]
29
6
[ 0  7 16 12  0 18 27 25 19 26]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [15]:
array_12 = np.random.randint(1,101,15)
print(array_12)
ordenado = np.sort(array_12)
print(ordenado)

[ 16 100  76  66  75  74  32  22  67  32  74  29  45   6  90]
[  6  16  22  29  32  32  45  66  67  74  74  75  76  90 100]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [16]:
array_11 = np.random.randint(1,28,(4,4))
print(array_11)
resulado_suma = np.sum(array_11)
print(resulado_suma)

[[ 5 18 27 12]
 [19  7 16 10]
 [26  8  8 19]
 [22 15 25  5]]
242


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [27]:
array_12_2 = np.random.randint(1,11,(5,5))
print(array_12_2)

array_12_2_borde = array_12_2[:, :]

array_result = []

for a in array_12_2:
    a[0] = 1
    a[2] = 0
    array_result.append(a)

print(np.array(array_result))


[[ 5  2  7  7  6]
 [ 1  2  9  1  4]
 [ 2  7  4  9  6]
 [ 2  1  6 10  5]
 [10  8  5  1  7]]
[[ 1  2  0  7  6]
 [ 1  2  0  1  4]
 [ 1  7  0  9  6]
 [ 1  1  0 10  5]
 [ 1  8  0  1  7]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.