<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [1]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [42]:
array_1d = np.random.randint(0,10,10)
array_1d

array([6, 8, 4, 4, 0, 5, 9, 7, 3, 5], dtype=int32)

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [43]:
array_2d = np.reshape(array_1d, (2, 5))
print(array_2d)

[[6 8 4 4 0]
 [5 9 7 3 5]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [44]:
array_init = [0, 2, 0, 3, 0, 4, 0]
array_ejer_3 = np.array(array_init)
result = array_ejer_3[array_ejer_3 !=  0]
result


array([2, 3, 4])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [45]:
array_tres_x_tres = np.random.randint(0,2,(3,3))
array_tres_x_tres

array([[0, 0, 1],
       [1, 1, 0],
       [0, 0, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [46]:
array_10_numeros = np.random.randint(0,10,10)
print(array_10_numeros)
minimo = np.min(array_10_numeros)
print(minimo)
maximo = np.max(array_10_numeros)
print(maximo)

[7 2 4 3 3 9 6 2 3 4]
2
9


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [47]:
una_dimension = np.random.randint(0,10,10)
print(una_dimension)
una_dimension_inver = una_dimension[::-1]
print(una_dimension_inver)

[0 9 0 3 9 7 9 5 9 6]
[6 9 5 9 7 9 3 0 9 0]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [75]:
array_tridimensional = np.random.randint(1,25,(2,3,4))
print("Todos: ")
print(array_tridimensional)

valor_buscar = 15
result_buscar = array_tridimensional[array_tridimensional ==  valor_buscar]

if len(result_buscar) > 0:
    print(result_buscar[0])
else:
    print(f"No hay valor buscado: {valor_buscar}")

print("Primer Array: ")
print(array_tridimensional[0, :, :])

print("Ultima FIla Array: ")
print(array_tridimensional[1, 2, :])


Todos: 
[[[20  5  5 11]
  [13 18 10 13]
  [ 5  2 18 18]]

 [[21 19  9  2]
  [16 21  2  9]
  [ 6  3 18 20]]]
No hay valor buscado: 15
Primer Array: 
[[20  5  5 11]
 [13 18 10 13]
 [ 5  2 18 18]]
Ultima FIla Array: 
[ 6  3 18 20]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [91]:
array_tridimensional_7 = np.random.randint(1,31,(3,2,5))
print("Todos: ")
print(array_tridimensional_7)

print("Primer subarray: ")
print(array_tridimensional_7[0, :, (0,1)])

print("Segundo subarray: ")
print(array_tridimensional_7[(1,2), :, :])

Todos: 
[[[15 10  2 29  7]
  [ 4  7 24  3 18]]

 [[30 21 17 30 16]
  [13  4 21 24 19]]

 [[ 9 13 28  6 15]
  [28 24  1  5 16]]]
Primer subarray: 
[[15  4]
 [10  7]]
Segundo subarray: 
[[[30 21 17 30 16]
  [13  4 21 24 19]]

 [[ 9 13 28  6 15]
  [28 24  1  5 16]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.